// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::collections::BTreeMap;
#[allow(unused_imports)]
use sails_rs::{
    calls::{Activation, Call, Query, Remoting, RemotingAction},
    prelude::*,
    String,
};
pub struct AppFactory<R> {
    #[allow(dead_code)]
    remoting: R,
}
impl<R> AppFactory<R> {
    #[allow(unused)]
    pub fn new(remoting: R) -> Self {
        Self { remoting }
    }
}
impl<R: Remoting + Clone> traits::AppFactory for AppFactory<R> {
    type Args = R::Args;
    fn new(&self) -> impl Activation<Args = R::Args> {
        RemotingAction::<_, app_factory::io::New>::new(self.remoting.clone(), ())
    }
}

pub mod app_factory {
    use super::*;
    pub mod io {
        use super::*;
        use sails_rs::calls::ActionIo;
        pub struct New(());
        impl New {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <New as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for New {
            const ROUTE: &'static [u8] = &[12, 78, 101, 119];
            type Params = ();
            type Reply = ();
        }
    }
}
pub struct LowFileService<R> {
    remoting: R,
}
impl<R> LowFileService<R> {
    pub fn new(remoting: R) -> Self {
        Self { remoting }
    }
}
impl<R: Remoting + Clone> traits::LowFileService for LowFileService<R> {
    type Args = R::Args;
    fn set_user_data(
        &mut self,
        nombre: String,
        edad: u32,
        profesion: String,
        titulacion: String,
        ubicacion: String,
        certificaciones: Vec<String>,
        identi: String,
        public_key: Vec<u128>,
        email: String,
        nickname: String,
        private_key: Vec<u128>,
    ) -> impl Call<Output = String, Args = R::Args> {
        RemotingAction::<_, low_file_service::io::SetUserData>::new(
            self.remoting.clone(),
            (
                nombre,
                edad,
                profesion,
                titulacion,
                ubicacion,
                certificaciones,
                identi,
                public_key,
                email,
                nickname,
                private_key,
            ),
        )
    }
    fn get_user_data(&self) -> impl Query<Output = IoLowFileState, Args = R::Args> {
        RemotingAction::<_, low_file_service::io::GetUserData>::new(self.remoting.clone(), ())
    }
}

pub mod low_file_service {
    use super::*;

    pub mod io {
        use super::*;
        use sails_rs::calls::ActionIo;
        pub struct SetUserData(());
        impl SetUserData {
            #[allow(dead_code)]
            pub fn encode_call(
                nombre: String,
                edad: u32,
                profesion: String,
                titulacion: String,
                ubicacion: String,
                certificaciones: Vec<String>,
                identi: String,
                public_key: Vec<u128>,
                email: String,
                nickname: String,
                private_key: Vec<u128>,
            ) -> Vec<u8> {
                <SetUserData as ActionIo>::encode_call(&(
                    nombre,
                    edad,
                    profesion,
                    titulacion,
                    ubicacion,
                    certificaciones,
                    identi,
                    public_key,
                    email,
                    nickname,
                    private_key,
                ))
            }
        }
        impl ActionIo for SetUserData {
            const ROUTE: &'static [u8] = &[
                56, 76, 111, 119, 70, 105, 108, 101, 83, 101, 114, 118, 105, 99, 101, 44, 83, 101,
                116, 85, 115, 101, 114, 68, 97, 116, 97,
            ];
            type Params = (
                String,
                u32,
                String,
                String,
                String,
                Vec<String>,
                String,
                Vec<u128>,
                String,
                String,
                Vec<u128>,
            );
            type Reply = String;
        }
        pub struct GetUserData(());
        impl GetUserData {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <GetUserData as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for GetUserData {
            const ROUTE: &'static [u8] = &[
                56, 76, 111, 119, 70, 105, 108, 101, 83, 101, 114, 118, 105, 99, 101, 44, 71, 101,
                116, 85, 115, 101, 114, 68, 97, 116, 97,
            ];
            type Params = ();
            type Reply = super::IoLowFileState;
        }
    }
}
#[derive(PartialEq, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IoLowFileState {
    pub nombre: String,
    pub edad: u32,
    pub profesion: String,
    pub titulacion: String,
    pub ubicacion: String,
    pub certificaciones: Vec<String>,
    pub identi: String,
    pub public_key: Vec<u128>,
    pub private_key: Vec<u128>,
    pub email: String,
    pub nickname: String,
}

pub mod traits {
    use super::*;
    #[allow(dead_code)]
    pub trait AppFactory {
        type Args;
        #[allow(clippy::new_ret_no_self)]
        #[allow(clippy::wrong_self_convention)]
        fn new(&self) -> impl Activation<Args = Self::Args>;
    }

    #[allow(clippy::type_complexity)]
    pub trait LowFileService {
        type Args;
        fn set_user_data(
            &mut self,
            nombre: String,
            edad: u32,
            profesion: String,
            titulacion: String,
            ubicacion: String,
            certificaciones: Vec<String>,
            identi: String,
            public_key: Vec<u128>,
            email: String,
            nickname: String,
            private_key: Vec<u128>,
        ) -> impl Call<Output = String, Args = Self::Args>;
        fn get_user_data(&self) -> impl Query<Output = IoLowFileState, Args = Self::Args>;
    }
}
